### ISSUE TITLE
Unable to connect opendj when deployed to docker: invalid credentials

### ISSUE THREAD

**Issue by DallasP9124** [OpenIdentityPlatform/OpenDJ#186]
**Describe the bug**
When running ODJ in docker with ROOT_USER_DN and ROOT_USER_PASSWORD set, connection with a client fails with error of 'invalid credentials'

**To Reproduce**
1. Use the following docker-compose configuration:
```yaml
version: '3'

services:
    opendj:
        image: openidentityplatform/opendj:latest
        environment:
            PORT: 1389
            LDAPS_PORT: 1636
            BASE_DN: "dc=legio"
            ROOT_USER_DN: "cn=dallas"
            ROOT_PASSWORD: "password"
        ports:
            - 1389:1389
            - 1636:1636
```
2. Download or launch an LDAP client to connect with (using AD Explorer)
3. Enter connection information and credentials

**Expected behavior**
Would expect to login with credentials set in docker-compose file.

**Screenshots**
Image of configuration: https://pasteboard.co/rP5cCNImtrwg.png

**Desktop (please complete the following information):**
 - OS (of docker): Fedora release 33 
 - LDAP Client: AD Explorer

**Additional context**
Docker logs before and after attempting to connect are the same:
```
opendj_1  | Instance data Directory is empty. Creating new DJ instance
opendj_1  | BASE DN is dc=legio
opendj_1  | Password set to password
opendj_1  | Running /opt/opendj/bootstrap/setup.sh
opendj_1  | Setting up default OpenDJ instance
opendj_1  | Configuring Directory Server ..... Done.
opendj_1  | Configuring Certificates ..... Done.
opendj_1  | Creating Base Entry dc=legio ..... Done.
opendj_1  | Starting Directory Server ...... Done.
opendj_1  | To see basic server configuration status and configuration, you can launch
opendj_1  | /opt/opendj/bin/status
opendj_1  | Server Run Status:        Started
opendj_1  | OpenDJ is started
```
