### ISSUE TITLE
OpenDJ doesn't start when using Prometheus' jmx_exporter as javaagent parameter

### ISSUE THREAD

**Issue by kenan3008** [OpenIdentityPlatform/OpenDJ#83]
**Describe the bug**
I'm trying to convert JMX to Prometheus metrics using the official Prometheus plugin jmx_exporter (https://github.com/prometheus/jmx_exporter) as java agent. The problem is that when I use jmx_export jar as a -javaagent parameter, OpenDJ doesn't start. Application crashes during _script-util.sh execution with the following error:

```
FATAL ERROR in native method: processing of -javaagent failed
/opt/opendj/lib/_script-util.sh: line 136: 25300 Aborted                 "${OPENDJ_JAVA_BIN}" ${OPENDJ_JAVA_ARGS} org.opends.server.tools.CheckJVMVersion 2> /dev/null
ERROR:  The detected Java version could not be used with the set of Java
arguments -server -javaagent:/home/kenan/opendj/prometheus.jar.
The detected Java binary is: /usr/bin/java
You must specify the path to a valid Java 7 or higher version.
The procedure to follow is to set the environment variable OPENDJ_JAVA_HOME
to the root of a valid Java 7 installation.
If you want to have specific Java settings for each command line you must
edit the properties file specifying the Java binary and/or the Java arguments
for each command line.  The Java properties file is located in:
/opendj/config/java.properties.
```

**To Reproduce**
1. unpack opendj and run basic setup script with 
```
opendj/setup
    --cli --baseDN '{{ opendj_basedn }}'
    --addBaseEntry
    --ldapPort {{ opendj_ldap_port }}
    --adminConnectorPort {{ opendj_admin_port }}
    --rootUserDN '{{ ldap_admin_user }}'
    --rootUserPassword '{{ ldap_admin_pass }}'
    --no-prompt
    --noPropertiesFile
    --doNotStart"
```

2. Enable JMX on port 1689
```
opendj/bin/dsconfig set-connection-handler-prop --hostname localhost --port 4444 --bindDN "cn=Directory Manager" --bindPassword password --handler-name "JMX Connection Handler" --set enabled:true --set listen-port:1689 --trustAll --no-prompt

opendj/bin/dsconfig -h localhost -p 4444 -D "cn=Directory Manager" -w password -n set-root-dn-prop --add default-root-privilege-name:jmx-read --add default-root-privilege-name:jmx-write --add default-root-privilege-name:jmx-notify --trustAll --no-prompt
```

3. Download jmx_exporter (https://github.com/prometheus/jmx_exporter) java agent for Prometheus from `https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar`

4. Create a config file for jmx_exporter and name it config.yaml
```
---
startDelaySeconds: 0
username: cn=Directory Manager
password: password
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:1689/org.opends.server.protocols.jmx.client-unknown
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true

whitelistObjectNames:
  - "org.opends.server:Name=*,Rdn1=*,Rdn2=*"
  - "org.opends.server:Name=*,Rdn1=*,Rdn2=*,Rdn3=*"

rules:
  # ex: org.opends.server<Name=rootDSE, Rdn1=cn-monitor, Rdn2=cn-amRoot_Database_Environment><>
  - pattern: "org.opends.server<Name=(.+), Rdn1=cn-(.+), Rdn2=cn-(.+)><>(.+): (.+)"
    name: opendj_$3_$4
    value: $5
    labels:
      name: $1
      type: $2
      bean: $3
    attrNameSnakeCase: true

  #ex: org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-Disk_Space_Monitor,Rdn3=cn-userRoot_backend
  - pattern: "org.opends.server<Name=(.+), Rdn1=cn-(.+), Rdn2=cn-(.+), Rdn3=cn-(.+)><>(.+): (.+)"
    name: opendj_$3_$4_$5
    value: $6
    labels:
      name: $1
      type: $2
      bean: $3
    attrNameSnakeCase: true
```

5. Add java agent parameter to java args for start-ds. Replace line `start-ds.java-args=-server` in config/java.properties with `start-ds.java-args=-server -javaagent:/path/to/java/agent/jmx_prometheus_javaagent-0.12.0.jar=6543:/path/to/config/config.yaml`

6. Start the server with bin/start-ds. Error from description is shown on the console.

**Expected behavior**
OpenDJ would start and I would be able to access Prometheus metrics via http endpoint localhost:6543/metrics

**Additional context**
I tested with OpenDJ 4.4.2 using Java 11 (OpenJDK 11.0.3) and Java 8 (OpenJDK 1.8.0_212). I tried with JAVA_HOME and with OPENDJ_JAVA_HOME, no luck.

I also tested on old release of OpenDJ, 2.6, and I was able to start the server and access metrics there.

I think that fixing this problem would be beneficial for a lot of users. To the best of my knowledge, there is currently no other way to export metrics to Prometheus from OpenDJ.
